### ISSUE TITLE
Regression: Riven no longer builds on Rust 1.80.0

### ISSUE THREAD

**Issue by BMorinBlitz** [MingweiSamuel/Riven#77]
Probably need to communicate a MSRV?

```
error[E0658]: lint reasons are experimental
  --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/riven-2.61.0/src/req/token_bucket.rs:33:24
   |
33 |     #[allow(dead_code, reason = "false positive")]
   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #54503 <https://github.com/rust-lang/rust/issues/54503> for more information

error[E0658]: lint reasons are experimental
  --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/riven-2.61.0/src/req/token_bucket.rs:39:24
   |
39 |     #[allow(dead_code, reason = "false positive")]
   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #54503 <https://github.com/rust-lang/rust/issues/54503> for more information
```

**Comment by MingweiSamuel** [comment]
riven=2.61.1 now has a msrv of 1.71.1
